[package]
name = "thiserror"
version = "1.0.7"
authors = ["David Tolnay <dtolnay@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "derive(Error)"
repository = "https://github.com/dtolnay/thiserror"
documentation = "https://docs.rs/thiserror"
categories = ["rust-patterns"]
readme = "README.md"

[dependencies]
thiserror-impl = { version = "=1.0.7", path = "impl" }

[dev-dependencies]
anyhow = "1.0"
ref-cast = "1.0"
rustversion = "1.0"
trybuild = "1.0"

[workspace]
members = ["impl"]
