[package]
name = "thiserror"
version = "0.0.0"
authors = ["David Tolnay <dtolnay@gmail.com>"]
edition = "2018"

[dependencies]
thiserror-impl = { version = "0.0", path = "impl" }

[dev-dependencies]
anyhow = "1.0"

[workspace]
members = ["impl"]
